# Generated by Django 4.1.3 on 2022-12-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
